### ISSUE TITLE
odio closes on opening

### ISSUE THREAD

**Issue by ant-oine** [tari01/odio#1]
It's been a long time since I've used odio to extract and convert a SACD iso to integrate it into my streamer. I had never had a problem before but now the application closes as soon as it opens. I can't even see the window. I use Linux Mint 20.1 cinnamon 4.8.6 kernel 5.4.0-65. Do not hesitate to ask for additional information to understand the origin of the problem.

**Comment by tari01** [comment]
Thanks for reporting this. Can you please open a terminal, type "odio" and report back what it says?

**Comment by ant-oine** [comment]
Traceback (most recent call last):
  File "/usr/bin/odio", line 1039, in <module>
    Odio(False)
  File "/usr/lib/python3/dist-packages/odio/gtk.py", line 165, in __init__
    self.postinit()
  File "/usr/bin/odio", line 187, in postinit
    if APPDEBUG:
NameError: name 'APPDEBUG' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/var/crash/_usr_bin_odio.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/odio", line 1039, in <module>
    Odio(False)
  File "/usr/lib/python3/dist-packages/odio/gtk.py", line 165, in __init__
    self.postinit()
  File "/usr/bin/odio", line 187, in postinit
    if APPDEBUG:
NameError: name 'APPDEBUG' is not defined

**Comment by tari01** [comment]
I think it should be OK now. I have released version 21.1.31 - just do an update, Mint should pick it up.

Please come back if you find any more bugs...

**Comment by ant-oine** [comment]
Everything works perfectly, thanks. I'll open a new issue to request a useful feature about the tagging tool.
